// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Copy(arg1) {
  return window['go']['main']['App']['Copy'](arg1);
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function Handling(arg1, arg2) {
  return window['go']['main']['App']['Handling'](arg1, arg2);
}

export function Reload() {
  window['go']['main']['App']['Reload']();
}
