// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {str} from '../models';

export function GetModules():Promise<Array<str.Module>>;

export function GetRemoteModlues():Promise<Array<string>>;

export function Handling(arg1:string,arg2:string):Promise<string>;

export function Reload():void;

export function Copy(arg1:string):Promise<Error>;

export function GetConfig():Promise<string>;
